sudo: required
services:
  - docker

before_install:
  - docker build -t charlesjlamb/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run charlesjlamb/react-test npm test -- --coverage

after_success:
  - docker build -t charlesjlamb/multi-client ./client
  - docker build -t charlesjlamb/multi-nginx ./nginx
  - docker build -t charlesjlamb/multi-server ./server
  - docker build -t charlesjlamb/multi-worker ./worker

# Log in to the docker CLI
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
# PUSH IMAGES TO DOCKER HUB
  - docker push charlesjlamb/multi-client
  - docker push charlesjlamb/multi-nginx
  - docker push charlesjlamb/multi-server
  - docker push charlesjlamb/multi-worker
